build_image:
  variables:

  image: registry.freaxnx01.ch/mydocker-build/build-ci:latest

  services:
    - docker:dind

  before_script:
    # - docker info

  script:
    - curl -k -LO https://github.com/duplicati/duplicati/releases/download/v2.0.5.103-2.0.5.103_canary_2020-02-18/duplicati-2.0.5.103_canary_2020-02-18.zip
    - unzip duplicati-2.0.5.103_canary_2020-02-18.zip -d duplicati
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:latest .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest

  only:
    - master