build_image:
  variables:

  image: registry.freaxnx01.ch/mydocker-build/build-ci:latest

  services:
    - docker:dind

  before_script:
    # - docker info

  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:latest --build-arg DUPLICATI_DOWNLOAD_URL=$(cat latest-zip) .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest

  only:
    - master